---
pagetitle: "Documenting things"
format: 
  revealjs: 
    multiplex: true
    transition: fade
    height: 900
    width: 1600
   # fontcolor: "#262d36"
  #  highlight-style: a11y
   # code-line-numbers: false
editor: visual
---

##  {#documenting-things-title data-menu-title="Documenting Things"} 

## Documenting things: openly for future us

### Julia Stewart Lowndes

### posit::conf(2023)

::: notes
- My name is Julie Lowndes. I'm a marine ecologist and I grew up professionally in the R and Open science communities over past the 10 years. Documenting things has been a big part of shifting my career - Director of Openscapes. 
- I'm going to talk about how documenting things can build visibility for yourself and change culture across organizations, with examples from NASA and NOAA communities tackling climate change. 
:::

## Things | Future Us
  - Things - could be code, teaching resources, how to organize files in your group
  - Future Us - mindset beyond you and your computer
  
TODO: images: example documentation

:::notes
when I say things
when I say future us, I'm thinking of a mindset beyond you and your computer. So thinking about how what you document now can save hundreds of emails later asking where things are or how to do things.
:::

## Documenting things doesn't have to be painful 

<br>

### Have a place
### Have an audience 
### Format for readability, accessibility, and navigation

<br>

Plan today:

  - 5-min lightening talk (inspired by Jenny Bryan's Naming Things) 💙
  - 10-mins of stories (and hot takes)
  
:::notes
- I'm also here to say documenting things doesn't have to be painful to write and boring to read.
- I have 3 pieces of advice: 
- the plan for today 
:::

## [Have a place]

TODO: images: wiki, google doc, quarto book. 

It doesn't matter where at first, get it started. Write it down.

:::notes
This can be whatever software you have
transition: what's important about having a place is that it helps you write as you go - 
:::

## Write as you go

Develop the habit of writing things down in this place. 

Paste from your email/slack and put it here instead

Write in small bites - not looming all at once.

:::notes
you might find yourself writing it in an issue. depending, write it down in the doc itself. Like editing directly rather than adding a comment in a Google doc
:::

## Design for reuse

Design your docs in a way that can be moved around - important for maintenance over time

- Write in short bits - modular 

- Network it to other things, don't maintain content in 2 places.

  - These short bits can be linked from each other. Networked, not linear.

- Think of it like we have functions we call from another script. It lives one place

- Don't repeat yourself (DRY) (cite), Don't repeat others (?) (Instead of writing things twice, know where the information is so you can link to it)


TODO visual: Maybe: advice on GH usernames

:::notes

  - write it down, can be moved later. Helps with incremental writing and not having it loom.
  - this will evolve, like ggplot2. scripts call other packages. Think like that.
  - have a place. Something that would go in an email or slack — put it there instead.
:::

## [Have an audience]

You're writing this for someone. Picture talking to them. Not dry. Specific.

<br>

TODO Images: screenshots/text of Jenny Bryan's WTF, Stat545, Happy Git with R

Future You

## Write in an inclusive tone

Mindset: We're in this together (Future Us)

Write what you'd actually say / keep things relevant to that audience

When we write tutorials, we write them as if we're teaching them outloud. What you would say is included. And we design the code in chunks for learners.

TODO Images: R for Excel Users

:::notes
"We" not "you"

Inclusive
:::

## Share it

- "as open as possible, as closed as necessary" 
- shared online (**breadcrumbs**)

- can help you refine place quarto, rmarkdown, google docs

- consider contributors

IMAGE: github link to google docs. Not accessible to everyone. ok.

## [Format for readability, accessibility, and navigation]

- aesthetics matter, and don't have to be super time-consuming
- accessibility matters - can mean screenreaders, low bandwidth, paywalls/permissions, and much more
- navigation mtters - helping Future Us find what we need
  
## Headers and Slugs

Use section headers - you can link directly to them

- TODO IMAGE: Google Doc Bookmark, Quarto anchor

Name things with this in mind

- Naming things - list Jenny's 3 points & video links

Be Consistent -  Not "example" and then 2nd example has a diff name. Indenting.


## Alt text



## Use markdown 

TODO: Write out how to do these things: 

`code`

[link to the important part]() not just the word [here]()

<br>

...Transition: And whether or not you use Markdown - 

## Keyboard shortcuts

Arrow keys + shift + option

- TODO: GIF of this and embed :grimacing: 

Shift-command 8 for bullets

: more and more for emojis

:::notes
you can use keyboard shortcuts
:::

## Documenting things — what's possible from this

<br>

### Have a place
### Have an audience 
### Format for readability, accessibility, and navigation

:::notes
Transition: hopefully now you're interested in hearing some stories of what this looks like and what's possible from it

Next:

2 stories: NASA and NOAA Fisheries ecology teams

Movement building though shared documentation

:::



## Mentor onboarding

Documentation: 

- For public: nasa-openscapes.github.io/mentors. 
- For mentors: earthdata-cloud-cookbook/contributing/onboarding
- For us: approach-guide/mentors-framework/onboarding


## Julie focus

I have a notebook - daily writing is smaller and ideas are bigger. I have a place, it helps my mind unleash

## NASA Cloud Cookbook scope 

## TO THINK ABOUT: how does this tie back to the 3 lightning talks. Don't belabor
"When they were thinking about the Cookbook, they were really thinking about X"

- NASA Earthdata teams - purpose understanding Earth and climate change
- Image: early framing: carpentries lessons <> Cookbook <> proj pythia.


## NASA Cloud Cookbook Contributing

- fits with  Contributing section early. 
  - maintainance isn't terrible; onboarding new folks
  - increasing contributors
  
## NASA Cloud Cookbook policy
  
  - Moving to nasa.gov

## NOAA Fisheries scope
- Fisheries ecology teams - purpose (manage seafood)
- Champions Cohorts — documentation really key
- image: FayLab, FIMS 
  
## NOAA Fisheries movement building

- pathways: document event series; nmfs-opensci resource book, 

## NOAA Fisheries Open data policy
  - NOAA Fisheries open data policy
  - level up in job

## Closing hot takes

- it takes time. part of your job. 
- It can help people feel less lost and like they belong.
- emojis are important. So much angst and misunderstandings




## How to document things openly for future us:

### Have a place
### Have an audience 
### Format for readability, accessibility, and navigation

(revisit hook)

- With these 3 things I gave you with the lightening talk, this is possible
  - Doesn’t have to be painful, doesn’t have to be hard, can accomplish great things. 
  
## Thank you

TODO

## Resources 

TODO
